/* Generated By:JavaCC: Do not edit this line. GrammarParserConstants.java */
package minjavac.manualParser.grammar;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GrammarParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 7;
  /** RegularExpression Id. */
  int MULTILINE_COMMENT = 8;
  /** RegularExpression Id. */
  int ASSIGN = 9;
  /** RegularExpression Id. */
  int CHOICE = 10;
  /** RegularExpression Id. */
  int EOR = 11;
  /** RegularExpression Id. */
  int LAMBDA = 12;
  /** RegularExpression Id. */
  int ID = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTILINE_COMMENT>",
    "\"::=\"",
    "\"|\"",
    "\";\"",
    "\"#\"",
    "<ID>",
  };

}
